client:
  timeout: 1s
pinger:
  interval: 15s
  reloadInterval: 30s
bot:
  updateTimeout: 10
storage:
  connectTimeout: 1s
  writeTimeout: 1s
  database: "pinger"
  statusCollection: "statuses"
  targetsCollection: "targets"
  usersCollection: "users"
